services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=Claudiaj22- #optional
      - SUDO_PASSWORD=Claudiaj22- #optional
      - PWA_APPNAME=code-server #optional
    volumes:
      - /Docker/vscode/config:/config
      - /Docker:/Docker
    ports:
      - 8444:8443
    restart: unless-stopped

