services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Europe/London
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /Docker/crafty-controller/backups:/crafty/backups
        - /Docker/crafty-controller/logs:/crafty/logs
        - /Docker/crafty-controller/:/crafty/servers
        - /Docker/crafty-controller/:/crafty/app/config
        - /Docker/crafty-controller/:/crafty/import

