services:
  dockmon:
    image: darthnorse/dockmon:latest
    container_name: dockmon
    restart: unless-stopped
    ports:
      - "7040:443"
    environment:
      - TZ=Europe/London
    volumes:
      - /Docker/dockmon/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock